/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEventTarget.idl"
#include "nsIDOMDOMRequest.idl"

[scriptable, builtinclass, uuid(42610ac0-77b8-11e2-b92a-0800200c9a66)]
interface nsIDOMNfcSecureElement : nsIDOMEventTarget {
  /**
   * A secure element is a smart card chip that can hold
   * several different applications with the necessary security.
   * The most known secure element is the Universal Integrated Circuit Card (UICC)
   */

  /*[implicit_jscontext] attribute jsval onSecureElementActivated;
  [implicit_jscontext] attribute jsval onSecureElementDeactivated;
  [implicit_jscontext] attribute jsval onSecureElementTransaction;*/

  /**
   * Send request to open a logical channel defined by its
   * application identifier (AID)
   *
   * @param aid
   *        The Application Identifier of the Applet to be selected on this channel
   * return value : An instance of Channel (channelID) if available or null.
   */
  nsIDOMDOMRequest iccOpenChannel(in DOMString aid);

  /**
   * Interface, used to communicate with an applet through the
   * Application Data Protocol Units (APDUs) and is
   * used for all data that is exchanged between the UICC card and the terminal (ME).
   *
   * @param channel
   *        The Application Identifier of the Applet to which APDU is directed
   * @param apdu
   *        Application Protocol Data Unit
   * return value : Response APDU
   */
  nsIDOMDOMRequest iccExchangeAPDU(in long channel, in jsval apdu);

  /**
   * Send request to close the selected logical channel identified by its
   * application identifier (AID)
   *
   * @param aid
   *        The Application Identifier of the Applet , to be closed
   */
  nsIDOMDOMRequest iccCloseChannel(in long channel);
};
